name: Continuous Integration
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install spatialite
      run: |
        sudo apt-get update
        sudo apt-get install sqlite3 libsqlite3-mod-spatialite
        sudo dpkg -L libsqlite3-mod-spatialite
    - name: Test
      run: |
        git clone https://github.com/mapbox/tippecanoe.git
        cd tippecanoe
        make -j
        make install
          
